tyomoranmas/nagano_cake

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/controllers/end_users/ship_addresses_controller.rb
- app/controllers/end_users_controller.rb
- app/controllers/ship_addresses_controller.rb
- app/models/end_user.rb
- app/models/ship_address.rb
- app/views/end_users/edit.html.erb
- app/views/end_users/registrations/new.html.erb
- app/views/end_users/sessions/new.html.erb
- app/views/end_users/shared/_address_form.html.erb
- app/views/end_users/shared/_form.html.erb
- app/views/end_users/ship_addresses/edit.html.erb
- app/views/end_users/ship_addresses/index.html.erb
- app/views/end_users/show.html.erb
- app/views/layouts/_error_message.html.erb
- config/routes.rb
- ubuntu-bionic-18.04-cloudimg-console.log
・配送先一覧、登録、編集ページ追加
・配送先の新規登録、更新、削除機能追加
> add ship_address

- app/assets/javascripts/cart_items 2.coffee
- app/assets/javascripts/end_users/cart_items 2.coffee
- app/assets/javascripts/end_users/cart_items 3.coffee
- app/assets/javascripts/end_users/products 2.coffee
- app/assets/javascripts/end_users/products 3.coffee
- app/assets/stylesheets/end_users/cart_items 2.scss
- app/assets/stylesheets/end_users/products 2.scss
- app/controllers/application_controller.rb
- app/controllers/end_users/orders_controller.rb
- app/models/end_user.rb
- app/models/order.rb
- app/views/end_users/orders/confirm.html.erb
- app/views/end_users/orders/index.html.erb
- app/views/end_users/orders/new.html.erb
- app/views/end_users/orders/show.html.erb
- app/views/end_users/ship_addresses/edit.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- ubuntu-bionic-18.04-cloudimg-console.log
・注文情報入力機能が半分完成
・注文履歴一覧・詳細デザイン完成
> add views/orders

- app/controllers/end_users/orders_controller.rb
- app/views/end_users/orders/confirm.html.erb
- app/views/end_users/orders/index.html.erb
- app/views/end_users/orders/new.html.erb
- app/views/end_users/show.html.erb
- config/routes.rb
> add order-system

- app/assets/stylesheets/application.scss
- app/controllers/end_users/orders_controller.rb
- app/models/ship_address.rb
- app/views/end_users/orders/confirm.html.erb
- app/views/end_users/orders/index.html.erb
- app/views/end_users/orders/new.html.erb
- app/views/end_users/orders/show.html.erb
- app/views/end_users/shared/_address_form.html.erb
- app/views/layouts/application.html.erb
- db/migrate/20200416063520_create_orders.rb
- db/schema.rb
- ubuntu-bionic-18.04-cloudimg-console.log
・注文情報入力機能ほとんど完成
・注文情報確認機能完成
・注文情報一覧完成
・注文情報詳細一部完成
> fix new-order

- test/controllers/end_users/orders_controller_test.rb
- test/controllers/end_users/products_controller_test.rb
- test/controllers/end_users/registrations_controller_test.rb
- test/controllers/end_users_controller_test.rb
- test/fixtures/end_users.yml
- test/fixtures/orders.yml
- test/test_helper.rb
- ubuntu-bionic-18.04-cloudimg-console.log
> add test/end_users/registration

- test/controllers/admins/orders_controller_test.rb
- test/controllers/admins/products_controller_test.rb
- test/controllers/end_users/products_controller_test.rb
> add /test/contcontrollers/admins/products_controller

- app/controllers/admins/orders_controller.rb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/show.html.erb
> fix admin/order

- app/controllers/admins/products_controller.rb
- app/models/genre.rb
- app/views/admins/products/show.html.erb
- app/views/layouts/_header.html.erb
#共通
-adminロゴのリンク先変更
#店側
-商品詳細の値段のカンマ
-商品編集後商品詳細へ移動
-ジャンル空での登録出来ないようバリデーション追加
> fix admin header

- app/controllers/end_users/cart_items_controller.rb
- app/controllers/end_users/orders_controller.rb
- app/controllers/end_users/ship_addresses_controller.rb
- app/controllers/end_users_controller.rb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/show.html.erb
- app/views/layouts/application.html.erb
> fix orders index show

- app/views/admins/products/index.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/_toggle.html.erb
--adminログアウト時にハンバーガー表示させないようにした
--ジャンルステータス「無効」の商品を店側商品一覧画面に表示させないようにした
> fix hambuger

- app/controllers/admins/orders_controller.rb
- app/controllers/end_users/cart_items_controller.rb
- app/controllers/end_users/products_controller.rb
- app/models/order.rb
- app/models/order_product.rb
- app/models/product.rb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/show.html.erb
- app/views/end_users/products/index.html.erb
- app/views/end_users/products/show.html.erb
> fix production_status

- app/assets/javascripts/application.js
- app/assets/javascripts/script.js
- app/controllers/end_users/orders_controller.rb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
・ハンバーガーメニューの読み込み修正
・カートアイテムが空の状態で注文情報入力ページに遷移しない
> fix hamburger-menu

- app/views/admins/products/edit.html.erb
- app/views/admins/products/index.html.erb
- app/views/admins/products/new.html.erb
- app/views/admins/products/show.html.erb
> Fix layout

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/admins/orders_controller.rb
- app/views/admins/end_users/index.html.erb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/show.html.erb
- app/views/admins/products/index.html.erb
・注文ステータスと製作ステータスを関連づけ、自動更新機能追加
> add relation status

- app/controllers/admins/products_controller.rb
- app/models/product.rb
- app/views/admins/products/edit.html.erb
- app/views/admins/products/new.html.erb
- app/views/admins/products/show.html.erb
##店側
-商品新規登録のバリデーション追加
- 商品新規登録、編集、詳細画面の画像サイズ調整
> [Add]validation to admin_product

- app/assets/stylesheets/application.scss
- app/controllers/end_users/orders_controller.rb
- app/controllers/end_users/products_controller.rb
- app/controllers/end_users_controller.rb
- app/views/admins/orders/show.html.erb
- app/views/end_users/products/index.html.erb
- app/views/end_users/products/top.html.erb
> fix end_users/product

- app/controllers/admins/products_controller.rb
> fix somewhere

- Gemfile
- Gemfile.lock
- app/controllers/admins/end_users_controller.rb
- app/controllers/admins/genres_controller.rb
- app/controllers/admins/products_controller.rb
- app/controllers/end_users/products_controller.rb
- app/models/end_user.rb
- app/models/genre.rb
- app/models/product.rb
- app/views/admins/end_users/edit.html.erb
- app/views/admins/genres/edit.html.erb
- app/views/admins/genres/index.html.erb
- app/views/admins/products/edit.html.erb
- app/views/admins/products/new.html.erb
- app/views/admins/products/show.html.erb
- app/views/end_users/edit.html.erb
- app/views/end_users/products/_genre_search.html.erb
- app/views/end_users/products/index.html.erb
- app/views/end_users/products/top.html.erb
- config/application.rb
- config/locales/ja.yml
・バリデーションチェック追加
・エラーメッセージ追加
・無効なジャンルに紐づく商品の非表示機能
> fix views/end_users/products

- app/controllers/admins/products_controller.rb
> fix admins/products_controller

- app/assets/stylesheets/admins/index.css
- app/views/admins/end_users/index.html.erb
- app/views/admins/orders/index.html.erb
> fix_layout
